# Generated by Django 2.0.7 on 2018-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmodel',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='imdb_id',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
    ]
