# Generated by Django 2.0.7 on 2018-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0002_auto_20181009_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='imdb_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
