# Generated by Django 2.0.7 on 2018-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0004_torrentmodel_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='quality',
            field=models.DecimalField(choices=[(0, '720p'), (1, '1080p')], decimal_places=0, max_digits=1),
        ),
    ]
