# Generated by Django 2.0.7 on 2018-10-17 15:44

import a_player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0005_auto_20181017_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentmodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='torrentmodel',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to=a_player.models.torrent_path),
        ),
    ]
