# Generated by Django 2.0.7 on 2018-10-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0006_auto_20181017_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrentmodel',
            old_name='name',
            new_name='file_name',
        ),
    ]
