# Generated by Django 2.0.7 on 2018-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0007_auto_20181017_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
