# Generated by Django 2.0.7 on 2018-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0008_torrentmodel_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentmodel',
            name='cover',
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
