# Generated by Django 2.0.7 on 2018-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0009_auto_20181029_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentmodel',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torrentmodel',
            name='film_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
