# Generated by Django 2.0.7 on 2018-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0010_auto_20181102_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='film_file',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
