# Generated by Django 2.0.7 on 2018-11-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0011_auto_20181102_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
