# Generated by Django 2.0.7 on 2018-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0013_filmhistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='en_sub',
            field=models.FileField(blank=True, null=True, upload_to='subtitles'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='ru_sub',
            field=models.FileField(blank=True, null=True, upload_to='subtitles'),
        ),
    ]
