# Generated by Django 2.0.7 on 2018-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0014_auto_20181113_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmmodel',
            old_name='en_sub',
            new_name='en_sub_srt',
        ),
        migrations.RenameField(
            model_name='filmmodel',
            old_name='ru_sub',
            new_name='ru_sub_srt',
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='en_sub_vtt',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='ru_sub_vtt',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
