# Generated by Django 2.0.7 on 2018-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0015_auto_20181113_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='tmd_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='torrentmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
