# Generated by Django 2.0.7 on 2018-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0015_auto_20181113_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
