# Generated by Django 2.0.7 on 2018-11-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0016_auto_20181120_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='ru_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
