# Generated by Django 2.0.7 on 2018-11-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_player', '0017_filmmodel_ru_info'),
        ('a_player', '0016_auto_20181116_1552'),
    ]

    operations = [
    ]
