# Generated by Django 2.0.7 on 2018-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_key_time',
            field=models.DateTimeField(null=True),
        ),
    ]
