# Generated by Django 2.0.7 on 2018-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180726_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_key_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
